# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Nota
author: Evan C.
logo: logo.png

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/evdcush/testing-pages  # Online location of your book
  path_to_book: '' # docs  # Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true

#

# WHAT: Excludes files from build that are not referenced in the toc.
# WHY:
#   - Otherwise, build fails with:
#    `WARNING: document isn't included in any toctree`
#   - Because I don't want an arbitrary `docs/` dir to hold docs
#     - I prefer keeping things flat and at root for fewer clicks
only_build_toc_files: true
